package com.redhat.demo.iot.datacenter.monitor
 
import com.redhat.demo.businessRules.DataSet;

rule "VoltageTooLow"
	lock-on-active true
	when
		$t : DataSet( deviceType == "voltage", payload < 2000 )
	then
		System.out.println("Rule 'low voltage' fired as voltage is " + $t.getPayload() + " with clipping at 2000");
		$t.setRequired(0);
		$t.setErrorCode(1);
		$t.setErrorMessage("Voltage too low");
		update( $t );
		
end 

rule "TemperatureTooHigh"
	lock-on-active true
	when
		$t : DataSet( deviceType == "temperature", payload > 27 )
	then
		System.out.println("Rule 'high temperature' fired as temperature is " + $t.getPayload() + " with clipping at 27");
		$t.setRequired(0);
		$t.setErrorCode(2);
		$t.setErrorMessage("Temperature too high");
		System.out.println("Temperature too high");
		update( $t );
		
end 